name: FlashFeed Quick Deploy (Legacy)

# This workflow is kept for backwards compatibility
# Use deploy.yml for production deployments
on:
  workflow_dispatch:
    inputs:
      deploy_reason:
        description: 'Reason for manual deployment'
        required: true
        default: 'Quick deploy without full CI/CD'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Tests nur ausführen wenn commit message "[test]" enthält
  test:
    if: contains(github.event.head_commit.message, '[test]')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        
    - name: Install Dependencies
      run: flutter pub get
      working-directory: ./
      
    - name: Run Unit Tests
      run: |
        flutter test --reporter=expanded
      working-directory: ./

    - name: Test Summary
      run: echo "✅ All tests passed! Proceeding with deployment..."

  build:
    # Build läuft immer, aber wartet auf Tests wenn sie ausgeführt werden
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Skip if tests failed
      if: needs.test.result == 'failure'
      run: |
        echo "❌ Tests failed - skipping deployment"
        exit 1
        
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        
    - name: Install Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Enable Web Support
      run: flutter config --enable-web
      working-directory: ./

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Build Web App
      run: flutter build web --release --base-href "/FlashFeed/"
      working-directory: ./

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4